replaced fake data in schedule with mongodb data
VandyHacks/fluffy-bubbles pull request #5
Opened 2023-04-04 02:18 UTC by shansitads

- Deleted fake data generation files
- Added a `mongo_manager.py` file with a `getNextNEvents()` function connects to mongodb and returns event data
- Client URI is a string in the `mongo_config.py` file (also added this file to `.gitignore`)
- Schedule command displays TBD if location information is missing

Output now looks like this:

<img width="421" alt="Screenshot 2023-04-03 at 9 17 12 PM" src="https://user-images.githubusercontent.com/52425323/229669673-deb13569-2113-4373-b130-c53a308660dd.png">

2023-04-05 14:54 UTC, agarg-usa requested changes

2023-04-05 14:54 UTC, agarg-usa commented on mongo_manager.py
> +    client = pymongo.MongoClient(CLIENT_URI)
how we would want to design this file is that we actually have a singleton pattern class that we use, and this class will store in it a variable called client, which we will then try to connect to the server / initialize this server somewhere in main.

This is so that for every request we do not have to reconnect to our mongoDB client but only once

2023-04-05 20:27 UTC, shansitads commented on mongo_manager.py
> +    client = pymongo.MongoClient(CLIENT_URI)
gotcha, should I move `db = client["witness-vhix"]` into the singleton class too?

2023-04-06 18:38 UTC, agarg-usa commented on cogs/general.py
> +                mongoInstance.db.events.find().sort("startTime", pymongo.ASCENDING)
ok wait actually we should probably discuss in our meeting whether we want to use pymongo or something like https://github.com/mongodb/motor as that allows for asyncio support so that we don't have to block the thread / process everytime we try to query to our DB

2023-04-08 08:51 UTC, davidzeng0 commented on cogs/general.py
> +                mongoInstance.db.events.find().sort("startTime", pymongo.ASCENDING)
look how well i raised him
he's a grown up now
reviewing pull requests with amazing insights
i cannot be happier

2023-04-13 23:18 UTC, merged